"""Run through browser-harness stdin after opening the local homepage."""
import time, json, pathlib

goto_url('http://localhost:3000')
wait_for_load()
time.sleep(1)
cdp('Emulation.setDeviceMetricsOverride', width=1440, height=900, deviceScaleFactor=1, mobile=False)
checks = []

def check(name, expression):
    passed = bool(js(expression))
    checks.append({'name': name, 'passed': passed})
    print(name, passed)
    if not passed:
        raise AssertionError(name)

js("document.querySelectorAll('#hero-dots button')[0].click()")
time.sleep(.1)
js("document.getElementById('hero-next').click()")
time.sleep(.1)
check('carousel next', "document.querySelector('.hero-slide.is-active').dataset.index==='1'")
js("document.getElementById('hero-prev').click()")
time.sleep(.1)
check('carousel previous', "document.querySelector('.hero-slide.is-active').dataset.index==='0'")
js("document.getElementById('search-btn').click()")
check('search opens', "!document.getElementById('search-modal').classList.contains('hidden')")
js("let i=document.getElementById('search-input');i.value='\u96f7\u8fbe';i.dispatchEvent(new Event('input',{bubbles:true}))")
check('search results', "document.querySelectorAll('#search-results a').length>0")
js("document.querySelector('#search-results a').click()")
check('search result closes modal', "document.getElementById('search-modal').classList.contains('hidden')")
js("document.querySelector('footer .open-privacy').click()")
check('footer privacy stays local', "location.host==='localhost:3000'&&!document.getElementById('privacy-modal').classList.contains('hidden')")
js("document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))")
check('escape closes privacy', "document.getElementById('privacy-modal').classList.contains('hidden')")
js("document.querySelector('#navbar a[href=\"#business\"]').click()")
check('isolated business overview', "document.getElementById('hero').classList.contains('view-hidden')&&!document.getElementById('business').classList.contains('view-hidden')")
js("document.querySelector('#navbar a[href=\"#hero\"]').click()")
check('home restored', "!document.getElementById('hero').classList.contains('view-hidden')")
check('form rejects empty', "!document.getElementById('contact-form').checkValidity()")
js("let f=document.getElementById('contact-form');for(let [n,v] of Object.entries({name:'Local QA',phone:'13800000000',email:'test@example.com',message:'Local demo validation'})){f.elements.namedItem(n).value=v;f.elements.namedItem(n).dispatchEvent(new Event('input',{bubbles:true}));}f.querySelector('input[type=checkbox]').checked=true;f.requestSubmit();")
time.sleep(.2)
check('local form acknowledgement', "document.querySelector('[role=status]')?.textContent.includes('\u4fe1\u606f\u672a\u53d1\u9001')")
cdp('Emulation.setDeviceMetricsOverride', width=390, height=900, deviceScaleFactor=1, mobile=False)
js("document.getElementById('menu-toggle').click()")
time.sleep(.4)
check('mobile drawer opens', "document.getElementById('mobile-menu').classList.contains('is-open')&&document.body.classList.contains('overflow-hidden')")
js("document.getElementById('menu-mask').click()")
check('mobile mask closes', "!document.getElementById('mobile-menu').classList.contains('is-open')")
js("document.querySelector('.lang-toggle').click()")
check('English toggle', "document.documentElement.lang==='en'&&document.body.textContent.includes('Business')")
js("document.querySelector('.lang-toggle').click()")
check('Chinese toggle', "document.documentElement.lang==='zh-CN'")
pathlib.Path('H:/ai-workspace/codes/official-website-refactor/docs/research/www-racodf-com-3880565d/root-8a5edab2/qa-interactions.json').write_text(json.dumps(checks, indent=2), encoding='utf-8')
